// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/habibiiberahim/go-backend/config"
	"github.com/habibiiberahim/go-backend/controller"
	"github.com/habibiiberahim/go-backend/repository"
	"github.com/habibiiberahim/go-backend/service"
)

// Injectors from injector.go:

func InitializedServer() controller.UserController {
	configConfig := config.NewConfiguration()
	db := config.NewGormDatabase(configConfig)
	userRepositoryImpl := repository.NewUserRepository(db)
	userServiceImpl := service.NewUserService(userRepositoryImpl)
	userControllerImpl := controller.NewUserController(userServiceImpl)
	return userControllerImpl
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)), service.NewUserService, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)), controller.NewUserController, wire.Bind(new(controller.UserController), new(*controller.UserControllerImpl)))
